Use variables for paths.

diff --git a/debian/landscape-base.postinst b/debian/landscape-base.postinst
--- a/debian/landscape-base.postinst
+++ b/debian/landscape-base.postinst
@@ -16,33 +16,38 @@ set -e
 . /usr/share/debconf/confmodule
 trap "db_stop || true" EXIT HUP INT QUIT TERM
 
+CFGDIR=/etc/landscape
+DATADIR=/var/lib/landscape
+LOGDIR=/var/log/landscape
+USER=landscape
+GROUP=landscape
+
 case "$1" in
     configure)
 
         # Create landscape system user
-        if ! getent passwd landscape >/dev/null; then
+        if ! getent passwd $USER >/dev/null; then
             adduser --quiet --system --group --disabled-password \
-                --home /var/lib/landscape --no-create-home landscape
-            touch /var/lib/landscape/.cleanup.user
+                --home $DATADIR --no-create-home $USER
+            touch $DATADIR/.cleanup.user
         fi
 
         # Create landscape system group (for <= 1.0.29.1-0ubuntu0.9.04.0)
-        if ! getent group landscape >/dev/null; then
-            addgroup --quiet --system landscape
-            touch /var/lib/landscape/.cleanup.group
+        if ! getent group $GROUP >/dev/null; then
+            addgroup --quiet --system $GROUP
+            touch $DATADIR/.cleanup.group
         fi
 
         # Ensure primary group is landscape (for <= 1.0.29.1-0ubuntu0.9.04.0)
-        if ! usermod -g landscape landscape > /dev/null 2>&1; then
-          echo "ERROR: usermod -g landscape landscape failed."
+        if ! usermod -g $GROUP $USER > /dev/null 2>&1; then
+          echo "ERROR: usermod -g $GROUP $USER failed."
         fi
 
         # Fix ownerships.
-        chown -R root:landscape /etc/landscape
-        chmod 0775 /etc/landscape/
-        chown -R landscape:landscape /var/lib/landscape
-        chown -R landscape:landscape /var/log/landscape
-
+        chown -R root:$GROUP $CFGDIR
+        chmod 0775 $CFGDIR
+        chown -R $USER:$GROUP $DATADIR
+        chown -R $USER:$GROUP $LOGDIR
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
