Merged kees' and Colin's changes

diff --git a/debian/landscape-client.postinst b/debian/landscape-client.postinst
--- a/debian/landscape-client.postinst
+++ b/debian/landscape-client.postinst
@@ -1,6 +1,20 @@
 #!/bin/sh
 set -e
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+. /usr/share/debconf/confmodule
+
 PACKAGE=landscape-client
 
 # Use the default installed Python.  Running just "python" might run
@@ -8,95 +22,107 @@ PACKAGE=landscape-client
 # running the landscape client.
 PYTHON=/usr/bin/python
 
-# 0.9.1 introduces non-backwards compatible changes.  This detects
-# whether or not the data is in the current format.  If not, all
-# existing data is removed.
-DATA_DIR=/var/lib/landscape
+case "$1" in
+    configure)
 
-if [ -d $DATA_DIR/data ]; then
-    rm -rf $DATA_DIR/*
-elif [ -f $DATA_DIR/client/data.bpickle ]; then
-    LAST_BYTE=`sed -n '$,$s/.*\(.\)/\1/p' $DATA_DIR/client/data.bpickle`
-    if [ "$LAST_BYTE" = e ]; then
-        rm -rf $DATA_DIR/*
-    fi
-fi
+        # 0.9.1 introduces non-backwards compatible changes.  This detects
+        # whether or not the data is in the current format.  If not, all
+        # existing data is removed.
+        DATA_DIR=/var/lib/landscape
 
-# Add the 'landscape' system user, if one isn't already present.
+        if [ -d $DATA_DIR/data ]; then
+            rm -rf $DATA_DIR/*
+        elif [ -f $DATA_DIR/client/data.bpickle ]; then
+            LAST_BYTE=`sed -n '$,$s/.*\(.\)/\1/p' $DATA_DIR/client/data.bpickle`
+            if [ "$LAST_BYTE" = e ]; then
+                rm -rf $DATA_DIR/*
+            fi
+        fi
 
-test "$1" = "configure" || exit 0
+        # Create landscape system user
+        if ! getent passwd landscape >/dev/null; then
+            adduser --quiet --system --disabled-password \
+                --gecos "Landscape Client Daemon" \
+                --home /var/lib/landscape --no-create-home landscape
+        fi
 
-getent passwd landscape >/dev/null || \
-  adduser --system --home /var/lib/landscape --no-create-home landscape
+        # Fix prior ownerships
+        chown -R landscape /var/log/landscape /var/lib/landscape
 
-chown -R landscape /var/log/landscape /var/lib/landscape
-
-CONFIG_FILE=/etc/landscape/client.conf
-if [ ! -f $CONFIG_FILE ]; then
-  cat > $CONFIG_FILE <<END
+        CONFIG_FILE=/etc/landscape/client.conf
+        if [ ! -f $CONFIG_FILE ]; then
+            # Create new configuration, with private mode
+            TEMPFILE=$(mktemp -p /etc/landscape)
+            cat > $TEMPFILE <<END
 [client]
 log_level = info
 url = https://landscape.canonical.com/message-system
 ping_url = http://landscape.canonical.com/ping
 data_path = /var/lib/landscape/client
 END
+            chown landscape $TEMPFILE
+            mv $TEMPFILE $CONFIG_FILE
 
-  chown landscape $CONFIG_FILE
+            # Do debconf configuration
+            db_get $PACKAGE/register_system
+            if [ "$RET" = true ]; then
+                priority=high
+            else
+                priority=medium
+            fi
+            db_input "$priority" $PACKAGE/computer_title || true
+            db_input "$priority" $PACKAGE/account_name || true
+            db_input "$priority" $PACKAGE/registration_password || true
+            db_go || true
 
-  # In case the configuration doesn't yet exist, try to run debconf to
-  # get the client registered.
+            db_get $PACKAGE/computer_title
+            COMPUTER_TITLE="${RET}"
+            db_get $PACKAGE/account_name
+            ACCOUNT_NAME="${RET}"
+            db_get $PACKAGE/registration_password
+            REGISTRATION_PASSWORD="${RET}"
 
-  . /usr/share/debconf/confmodule
+            # If we got the needed information, actually do the registration.
+            if [ -n "$ACCOUNT_NAME" ]; then
+                landscape-config --silent -a "$ACCOUNT_NAME" \
+                                          -p "$REGISTRATION_PASSWORD" \
+                                          -t "$COMPUTER_TITLE"
+            fi
+        else
+            # Fix non-private permissions
+            chmod 0600 $CONFIG_FILE
+        fi
 
-  # Do debconf configuration
-  db_get $PACKAGE/computer_title
-  COMPUTER_TITLE="${RET}"
-  db_get $PACKAGE/account_name
-  ACCOUNT_NAME="${RET}"
-  db_get $PACKAGE/registration_password
-  REGISTRATION_PASSWORD="${RET}"
+        # old monolithic clients have a single persist data file and a single
+        # package hash db.  This data should be migrated to the new format
+        # where each service has a persist and the package data is kept in a
+        # sqlite database.
 
-  db_stop
+        DATA_BPICKLE=$DATA_DIR/client/data.bpickle
+        BROKER_BPICKLE=$DATA_DIR/client/broker.bpickle
 
-  # If we got the needed information, actually do the registration.
-  if [ -n "$ACCOUNT_NAME" ]; then
-    landscape-config --silent -a "$ACCOUNT_NAME" \
-                              -p "$REGISTRATION_PASSWORD" \
-                              -t "$COMPUTER_TITLE"
-  fi
+        if [ -f $DATA_BPICKLE -a ! -f $BROKER_BPICKLE ]; then
+            $PYTHON -c "from landscape.upgraders import legacy; legacy.migrate_data_file('$DATA_DIR/client')"
+            mv $DATA_BPICKLE $DATA_BPICKLE.migrated
+            echo "Old monolithic client data file migrated to new format."
+        fi
 
-fi
+        # Tell dbus to reload its configuration since we've installed a conf
+        # to its system.d
+        invoke-rc.d dbus reload || true
+    ;;
 
-# old monolithic clients have a single persist data file and a single
-# package hash db.  This data should be migrated to the new format
-# where each service has a persist and the package data is kept in a
-# sqlite database.
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 
-DATA_BPICKLE=$DATA_DIR/client/data.bpickle
-BROKER_BPICKLE=$DATA_DIR/client/broker.bpickle
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
-if [ -f $DATA_BPICKLE -a ! -f $BROKER_BPICKLE ]; then
-  $PYTHON -c "from landscape.upgraders import legacy; legacy.migrate_data_file('$DATA_DIR/client')"
-  mv $DATA_BPICKLE $DATA_BPICKLE.migrated
-  echo "Old monolithic client data file migrated to new format."
-fi
-
-# Tell dbus to reload its configuration since we've installed a conf to its
-# system.d
-invoke-rc.d dbus reload
-
-# This is a cleanup of permissions on the smart directory
-find /var/lib/smart -type f -exec chmod 0644 {} \;
-find /var/lib/smart -type d -exec chmod 0755 {} \;
-
-# This is a cleanup of the ownership of the log files.  See bug #215372.
-LOCK_DIR=/var/lib/landscape/client/package
-test -f $LOCK_DIR/reporter.lock && chown landscape:root $LOCK_DIR/reporter.lock
-
-# Update start order if needed.  See bug #227414.
-if ls /etc/rc*.d/S20landscape-client > /dev/null 2>&1; then
-    update-rc.d -f landscape-client remove > /dev/null
-fi
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
diff --git a/debian/landscape-client.postrm b/debian/landscape-client.postrm
--- a/debian/landscape-client.postrm
+++ b/debian/landscape-client.postrm
@@ -1,11 +1,36 @@
 #!/bin/sh
 set -e
 
-test "$1" = "purge" || exit 0
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-update-rc.d landscape-client remove >/dev/null || exit $?
-getent passwd landscape >/dev/null || exit 0
-! deluser --version >/dev/null 2>&1 || exec deluser landscape
-echo 'deluser program not available, not removing system user "landscape".' >&2
+case "$1" in
+    purge)
+        deluser --quiet --system landscape >/dev/null || true
+    ;;
+
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
