Remove the user and group if we added them.

diff --git a/debian/landscape-common.postrm b/debian/landscape-common.postrm
--- a/debian/landscape-common.postrm
+++ b/debian/landscape-common.postrm
@@ -16,7 +16,15 @@ set -e
 
 case "$1" in
     purge)
-        deluser --quiet --system landscape >/dev/null || true
+        # Clean up the landscape user.
+        if [ -f /var/lib/landscape/.cleanup.user ]; then
+            deluser --quiet --system landscape >/dev/null || true
+            rm -f /var/lib/landscape/.cleanup.user
+            if [ -f /var/lib/landscape/.cleanup.group ]; then
+                delgroup --quiet --system landscape >/dev/null || true
+            fi
+        fi
+        rm -f /var/lib/landscape/.cleanup.group
     ;;
 
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
