Use tabs for consistency

diff --git a/debian/landscape-client.init b/debian/landscape-client.init
--- a/debian/landscape-client.init
+++ b/debian/landscape-client.init
@@ -59,15 +59,15 @@ case "$1" in
 			mkdir $PIDDIR
 			chown landscape $PIDDIR
 		fi
-                # Cleanup leftover sockets there's no other landscape process
-                # running. This shouldn't be usually necessary, but it can
-                # happen in case the client crashed badly and the socket points
-                # to a process with the same PID.
-                if ls $SOCKETDIR/* > /dev/null 2>&1; then
-                    if ! pidofproc -p $PIDFILE $DAEMON > /dev/null; then
-                        rm -f $SOCKETDIR/*
-                    fi
-                fi
+		# Cleanup leftover sockets there's no other landscape process
+		# running. This shouldn't be usually necessary, but it can
+		# happen in case the client crashed badly and the socket points
+		# to a process with the same PID.
+		if ls $SOCKETDIR/* > /dev/null 2>&1; then
+			if ! pidofproc -p $PIDFILE $DAEMON > /dev/null; then
+                		rm -f $SOCKETDIR/*
+			fi
+		fi
 		FULL_COMMAND="start-stop-daemon --start --quiet --oknodo --startas $DAEMON --pidfile $PIDFILE -g $DAEMON_GROUP -- --daemon --pid-file $PIDFILE"
 		if [ x"$DAEMON_USER" != x ]; then
 			sudo -u $DAEMON_USER $FULL_COMMAND
