fix indentation

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -14,17 +14,17 @@ jobs:
     strategy:
       matrix:
         runner: ["ubuntu-24.04", "ubuntu-22.04"]
-      runs-on: ${{ matrix.runner }}
-      steps:
-        # Many of the tests require root privileges, so the tests run using sudo.
-        - uses: actions/checkout@v5
+    runs-on: ${{ matrix.runner }}
+    steps:
+      # Many of the tests require root privileges, so the tests run using sudo.
+      - uses: actions/checkout@v5
 
-        # In 22.04, the pytest executable was called py.test-3.
-        # We attempt to symlink it to pytest, not worrying if the linking fails.
-        - name: install python dependencies
-          run: |
-            make depends-ci
-            sudo ln -s /usr/bin/py.test-3 /usr/bin/pytest || true
+      # In 22.04, the pytest executable was called py.test-3.
+      # We attempt to symlink it to pytest, not worrying if the linking fails.
+      - name: install python dependencies
+        run: |
+          make depends-ci
+          sudo ln -s /usr/bin/py.test-3 /usr/bin/pytest || true
 
-        - name: run pytest integration tests
-          run: sudo pytest -m integration
+      - name: run pytest integration tests
+        run: sudo pytest -m integration
